// <auto-generated />
using BookSelling_E_Comerse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookSelling_E_Comerse.Migrations
{
    [DbContext(typeof(ApplicatioDbContext))]
    [Migration("20240401152116_SeedCategorysTable")]
    partial class SeedCategorysTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookSelling_E_Comerse.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayOreder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOreder = "5",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOreder = "3",
                            Name = "Program"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOreder = "2",
                            Name = "History"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
